engines:
  duplication:
    enabled: true
    config:
      languages:
      - c
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
  gnu-complexity:
    enabled: true
    config:
      threshold: 20
  shellcheck:
    enabled: true
ratings:
  paths:
  - include/
  - lib/
  - plugins/
  - tests/
exclude_paths:
- "**.sample"
- compile
- config.sub 
- depcomp
- install-sh
- libtool
- ltmain.sh
- m4/
