language: c

compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "WqpTr19IWav//MQEQ7RcerdTVhbYt9faBh2QoEZmRLDPm+0RBidw1kvP73Di9pozURqisdB1P5LJ5eVFuocaD2eM+pO4399hHD48QsupDoLxgcJfmeP5YfT7Kmq97vyOs5dV01uopRMTJ9SDD1rt2oia+Ez6B/AeTCEpENb/76Y="

addons:
  coverity_scan:
    project:
      name: "madrisan/nagios-plugins-linux"
      description: "Nagios Plugins for Linux"
    notification_email: davide.madrisan@gmail.com
    # Commands to prepare for build_command
    build_command_prepend: "autoreconf -v -Wall -i -Im4 && ./configure"
    # This command will be added as an argument to "cov-build" to compile
    # the project for analisys
    build_command: "make clean all"
    branch_pattern: master

#before_script:
#  - autoreconf -v -Wall -i -Im4
#  - ./configure || { cat config.log; false; }

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make clean all; fi
