name: Build check

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    types: [assigned, edited, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        os: [buster, fedora_latest, ubuntu-latest]
        experimental: [alpine_latest]
        include:
        - os: buster
          COMPILER: gcc
          LINKER: gcc

    steps:
    - uses: actions/checkout@v2

    - name: configure
      run: |
        autoreconf --install
        ./configure

    - name: make
      run: make

    - name: make check
      run: make check

    - name: make distcheck
      run: make distcheck
